version: "1"
services:
  mongo_db:
    image: mongo
    container_name: "mongo_db"
    ports:
      - 27023:27017
  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - 6379:6379
  mail-storage:
#    image: mail-storage.jar
    container_name: mail-storage
    build: ../../../.
    ports:
      - 8080:8080
    links:
      - mongo_db